# Generated by Django 5.0.2 on 2024-04-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiogasProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_fvw', models.FloatField()),
                ('ratio_cow_manure', models.FloatField()),
                ('biogas_production', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WasteCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_content', models.FloatField()),
                ('vs_content', models.FloatField()),
            ],
        ),
    ]
