# Generated by Django 5.0.2 on 2024-04-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WasteCharacteristics',
        ),
        migrations.AddField(
            model_name='biogasproduction',
            name='moisture_content',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='biogasproduction',
            name='vs_content',
            field=models.FloatField(null=True),
        ),
    ]
