# Generated by Django 5.0.2 on 2024-04-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_wastecharacteristics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeterminationOfTotalSolids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_of_crucible', models.IntegerField()),
                ('weight_of_sample', models.IntegerField()),
                ('weight_of_dryresidue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeterminationOfVolatileSolids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_of_dryresidue', models.IntegerField()),
                ('weight_of_dryresidue_from_furnace', models.IntegerField()),
                ('weight_of_sample', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PercentageOfAsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_of_crucible', models.IntegerField()),
                ('weight_of_ash', models.IntegerField()),
                ('weight_of_sample', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PercentageOfCarbohydrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percentage_of_ash', models.IntegerField()),
                ('Percentage_of_protein', models.IntegerField()),
                ('Percentage_of_moisture', models.IntegerField()),
                ('Percentage_of_fat', models.IntegerField()),
                ('Percentage_of_fibre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PercentageOfFat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_of_flask', models.IntegerField()),
                ('weight_of_oil', models.IntegerField()),
                ('weight_of_empty_flask', models.IntegerField()),
                ('weight_of_sample', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PercentageOfFibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_of_dryresidue', models.IntegerField()),
                ('weight_of_sample', models.IntegerField()),
                ('weight_of_ash', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PercentageOfMoisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_of_crucible', models.IntegerField()),
                ('weight_of_sample', models.IntegerField()),
                ('weight_of_drymatter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PercentageOfProtein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percentage_of_nitrogen', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BiogasProduction',
        ),
    ]
